---
title: "reference"
author: "Saurav"
date: "3/9/2022"
output: html_document
css: styles.css
---

<h2>List of reference materials</h2>

<h2><a href = https://www.sciencedirect.com/science/article/pii/S2351989420305680> Soil Health Gap: A concept to establish a benchmark for soil health management </a></h2>

<p>Growing calls and the need for sustainable agriculture have brought deserved attention to soil and to efforts towards improving or maintaining soil health. Numerous research and field experiments report soil health in terms of physicochemical and biological indicators, and identify different management practices that can improve it. However, the question remains how much of cultivated land has degraded since the dawn of agriculture? What is the maximum or realistically attainable soil health goal? Determination of a benchmark that defines the true magnitude of degradation and simultaneously sets potential soil health goals will optimize efforts in improving soil health using different practices. In this paper, we discuss a new term "Soil Health Gap" that is defined as the difference between soil health in an undisturbed native soil and current soil health in a cropland in a given agroecosystem. Soil Health Gap can be determined based on a general or specific soil property such as soil carbon. Soil organic carbon were measured at native grassland, no-till, conventionally tilled, and subsoil exposed farmlands. Soil Health Gap based on soil organic carbon was in order of no-till \< conventional till \< subsoil exposed farmland and subsequently, maximum attainable soil health goal with introduction of conservation practices would vary by an existing management practice or condition. Soil Health Gap establishes a benchmark for soil health management decisions and goals and can be scaled up from site-specific to regional to global scale.</p>

<h2><a href = https://www.sciencedirect.com/science/article/pii/S1470160X22009414> Cropland Reference Ecological Unit: A land classification unit for comparative soil studies</a></h2>

<p>There is a growing consensus on a need for measuring the dynamic soil properties of croplands and even comparisons with a reference state or native land. These measurements and paired comparisons will create the capacity to determine soil health management effects and targets. However, the complex soil heterogeneity and climate variations make soil health potential variable and confound the effects of land-use and management practices and comparisons between soils from different sites. Identifying a discrete landmass unit where all soils have similar health potential will be critical in conducting meaningful comparative studies and measuring the impact of conservation practices. This methodological paper proposes and discusses a land unit, Cropland Reference Ecological Unit (CREU), that accounts for soil genoform and climate variabilities and covers an area with a presumably similar soil health potential. An example CREU has been developed, for one Major Land Resource Area (MLRA) in Nebraska, which is an area delineated based on the standard United States Department of Agriculture -- Natural Resources Conservation Service (USDA-NRCS) hierarchical land classification system. This example portrays an actual difference in soil health for different land use and agronomic management practices can be determined by comparing sites under the framework of CREU. Evaluation of management effects on soil health indicators in a CREU will adequately illustrate the beneficial impact of such practices without being confounded by agroecological variations. This proposed framework addresses researchers' current interest in comparing soil health parameters among croplands and reference sites to benchmark soil health measurements, set soil health targets, and determine the effects of different management practices.</p>
